### ISSUE TITLE
Order Filter Doesn't works On AdminPanel

### ISSUE THREAD

**Issue by ppeyman** [majidiyan/persian-datetime-picker#2]
Hi dear 
when i filtered order days just set to day 29 and doesn't show orders in specific date

![image](https://github.com/majidiyan/persian-datetime-picker/assets/13271466/167df1e8-3537-4236-8a19-35f1c3c64111)

Magento Version : 2.4.6-p3

and doesn't works!

**Comment by majidiyan** [comment]
This module works on Magento 2.4.3 and lower versions, in 2.4.6 needs to reproduce. do it yourself.
